#!/usr/bin/env bash
# Builds libass and the two libraries it will not do without, for the subtitle overlay
# the Jellyfin client draws on the graphics plane.
#
#   tools/build-libass.sh          # cross build, installs into the NDK sysroot
#   tools/build-libass.sh --host   # native build into build/libass-host
#
# libass requires FriBidi and HarfBuzz - neither is optional in 0.17 - and FreeType,
# which the TV already ships. Fontconfig is deliberately left out: it is present in the
# sysroot, but on the TV it would want a cache and a config of its own at startup, and
# the app names the font file itself (see docs/fonts.md). Its config there also maps every
# family to LG Display, so it would not find a style's font anyway: styles resolve to the
# fonts the container attaches, and otherwise fall back to that one face.
#
# FriBidi and HarfBuzz build with meson because that is all HarfBuzz has had since 8.0;
# the NDK ships a meson, but its cross file still carries the build machine's paths, so
# one is written here instead. libass itself is autotools and has nothing else.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

FRIBIDI_VERSION="${FRIBIDI_VERSION:-1.0.16}"
FRIBIDI_SHA256="${FRIBIDI_SHA256:-1b1cde5b235d40479e91be2f0e88a309e3214c8ab470ec8a2744d82a5a9ea05c}"
FRIBIDI_URL="${FRIBIDI_URL:-https://github.com/fribidi/fribidi/releases/download/v$FRIBIDI_VERSION/fribidi-$FRIBIDI_VERSION.tar.xz}"

HARFBUZZ_VERSION="${HARFBUZZ_VERSION:-11.5.0}"
HARFBUZZ_SHA256="${HARFBUZZ_SHA256:-2d30ba45c4c8ec4de661a1002b4f88d0841ff1a3087f34629275f5436d722109}"
HARFBUZZ_URL="${HARFBUZZ_URL:-https://github.com/harfbuzz/harfbuzz/releases/download/$HARFBUZZ_VERSION/harfbuzz-$HARFBUZZ_VERSION.tar.xz}"

LIBASS_VERSION="${LIBASS_VERSION:-0.17.4}"
LIBASS_SHA256="${LIBASS_SHA256:-78f1179b838d025e9c26e8fef33f8092f65611444ffa1bfc0cfac6a33511a05a}"
LIBASS_URL="${LIBASS_URL:-https://github.com/libass/libass/releases/download/$LIBASS_VERSION/libass-$LIBASS_VERSION.tar.xz}"

fetch() { # url sha256 destination
    echo "$2  $3" | sha256sum -c --status 2>/dev/null && return 0
    curl -fL --retry 3 -o "$3" "$1"
    echo "$2  $3" | sha256sum -c
}

unpack() { # archive destination
    rm -rf "$2"
    mkdir -p "$2"
    tar -xf "$1" -C "$2" --strip-components=1
}

HOST_BUILD=0
[ "${1:-}" = "--host" ] && HOST_BUILD=1

WORK="$ROOT/build"
mkdir -p "$WORK/downloads"

if [ "$HOST_BUILD" = 1 ]; then
    PREFIX="$WORK/libass-host"
    DESTDIR=""
    STAGED="$PREFIX"
    CROSS_ARGS=()
    CONFIGURE_ARGS=()
    export PKG_CONFIG_PATH="$PREFIX/lib/pkgconfig${PKG_CONFIG_PATH:+:$PKG_CONFIG_PATH}"
    MESON=meson
    READELF=readelf
else
    SDK="${WEBOS_SDK:-/opt/arm-webos-linux-gnueabi_sdk-buildroot}"
    [ -d "$SDK" ] || { echo "error: no webOS NDK at $SDK (set WEBOS_SDK)" >&2; exit 1; }
    SYSROOT="$SDK/arm-webos-linux-gnueabi/sysroot"
    CROSS="$SDK/bin/arm-webos-linux-gnueabi-"
    PREFIX=/usr/local/libass
    DESTDIR="$SYSROOT"
    STAGED="$SYSROOT$PREFIX"
    READELF="${CROSS}readelf"
    MESON=meson
    # Same ABI the app is compiled with: base soft-float ABI, real FPU. See device.md.
    ARCH_FLAGS="-mthumb -mcpu=cortex-a55 -mfpu=neon-vfpv4 -mfloat-abi=softfp"
    export PKG_CONFIG_LIBDIR="$SYSROOT$PREFIX/lib/pkgconfig:$SYSROOT/usr/lib/pkgconfig:$SYSROOT/usr/share/pkgconfig"
    export PKG_CONFIG_SYSROOT_DIR="$SYSROOT"
    CROSS_FILE="$WORK/libass-cross.ini"
    cat > "$CROSS_FILE" <<EOF
# Generated by tools/build-libass.sh. The NDK's own etc/meson/cross-compilation.conf
# still names the buildroot machine's paths, so it cannot be used as shipped.
[binaries]
c = '${CROSS}gcc'
cpp = '${CROSS}g++'
ar = '${CROSS}ar'
strip = '${CROSS}strip'
pkg-config = '$SDK/bin/pkg-config'

[built-in options]
c_args = ['--sysroot=$SYSROOT', $(printf "'%s', " $ARCH_FLAGS) '-Os']
cpp_args = ['--sysroot=$SYSROOT', $(printf "'%s', " $ARCH_FLAGS) '-Os']
c_link_args = ['--sysroot=$SYSROOT', $(printf "'%s', " $ARCH_FLAGS)]
cpp_link_args = ['--sysroot=$SYSROOT', $(printf "'%s', " $ARCH_FLAGS)]
wrap_mode = 'nodownload'

[properties]
needs_exe_wrapper = true
sys_root = '$SYSROOT'
pkg_config_libdir = '$PKG_CONFIG_LIBDIR'

[host_machine]
system = 'linux'
cpu_family = 'arm'
cpu = 'armv7a'
endian = 'little'
EOF
    CROSS_ARGS=(--cross-file "$CROSS_FILE")
    # The NDK's libtool archives still name the paths of the machine that built the SDK,
    # so linking anything against the sysroot's FreeType with libtool dies looking for a
    # libpng16.la under /__w. Rewriting the sysroot prefix in place is idempotent, and
    # this script already installs into that sysroot.
    sed -i "s|/[^ ']*/arm-webos-linux-gnueabi/sysroot/usr/lib|$SYSROOT/usr/lib|g" \
        "$SYSROOT"/usr/lib/*.la
    CONFIGURE_ARGS=(
        --host=arm-webos-linux-gnueabi
        CC="${CROSS}gcc"
        # Speed, not size, for libass itself: on the TV its C rasteriser is the cost of a
        # typeset sign, and -O2 in ARM state halves it against -Os in Thumb (an animated
        # intro averaged 64 ms a frame at -Os, 31 ms here). -O3 measured no better.
        CFLAGS="--sysroot=$SYSROOT $ARCH_FLAGS -O2 -marm"
        LDFLAGS="--sysroot=$SYSROOT $ARCH_FLAGS"
        PKG_CONFIG="$SDK/bin/pkg-config"
    )
fi

rm -rf "$STAGED"

# ------------------------------------------------------------------------ FriBidi
fetch "$FRIBIDI_URL" "$FRIBIDI_SHA256" "$WORK/downloads/fribidi-$FRIBIDI_VERSION.tar.xz"
unpack "$WORK/downloads/fribidi-$FRIBIDI_VERSION.tar.xz" "$WORK/fribidi-src"
rm -rf "$WORK/fribidi-build"
$MESON setup "$WORK/fribidi-build" "$WORK/fribidi-src" "${CROSS_ARGS[@]}" \
    --prefix="$PREFIX" --buildtype=release --default-library=shared \
    -Dbin=false -Ddocs=false -Dtests=false
$MESON compile -C "$WORK/fribidi-build"
DESTDIR="$DESTDIR" $MESON install -C "$WORK/fribidi-build" --no-rebuild

# ----------------------------------------------------------------------- HarfBuzz
# Only the shaper and its FreeType bridge: no GLib, no ICU, no Cairo, no subsetter.
fetch "$HARFBUZZ_URL" "$HARFBUZZ_SHA256" "$WORK/downloads/harfbuzz-$HARFBUZZ_VERSION.tar.xz"
unpack "$WORK/downloads/harfbuzz-$HARFBUZZ_VERSION.tar.xz" "$WORK/harfbuzz-src"
rm -rf "$WORK/harfbuzz-build"
$MESON setup "$WORK/harfbuzz-build" "$WORK/harfbuzz-src" "${CROSS_ARGS[@]}" \
    --prefix="$PREFIX" --buildtype=release --default-library=shared \
    -Dfreetype=enabled -Dglib=disabled -Dgobject=disabled -Dicu=disabled \
    -Dcairo=disabled -Dchafa=disabled -Dgraphite2=disabled \
    -Dtests=disabled -Ddocs=disabled -Dutilities=disabled -Dbenchmark=disabled
$MESON compile -C "$WORK/harfbuzz-build"
DESTDIR="$DESTDIR" $MESON install -C "$WORK/harfbuzz-build" --no-rebuild

# ------------------------------------------------------------------------- libass
fetch "$LIBASS_URL" "$LIBASS_SHA256" "$WORK/downloads/libass-$LIBASS_VERSION.tar.xz"
unpack "$WORK/downloads/libass-$LIBASS_VERSION.tar.xz" "$WORK/libass-src"
rm -rf "$WORK/libass-build"
mkdir -p "$WORK/libass-build"
cd "$WORK/libass-build"
"$WORK/libass-src/configure" \
    --prefix="$PREFIX" \
    --enable-shared --disable-static \
    --disable-fontconfig --disable-require-system-font-provider --disable-libunibreak \
    "${CONFIGURE_ARGS[@]}"
make -j"$(nproc)"
make install ${DESTDIR:+DESTDIR="$DESTDIR"}

# --------------------------------------------------------------------------- checks
for lib in libass libfribidi libharfbuzz; do
    ls "$STAGED/lib/$lib.so".* >/dev/null 2>&1 || {
        echo "error: $lib is missing" >&2; exit 1; }
done
# A provider left in would mean fontconfig at startup on a set that has no cache for it.
if "$READELF" -d "$STAGED/lib"/libass.so.* | grep -q "libfontconfig"; then
    echo "error: libass picked up fontconfig" >&2; exit 1
fi
for want in libfribidi libharfbuzz libfreetype; do
    "$READELF" -d "$STAGED/lib"/libass.so.* | grep -q "$want" || {
        echo "error: libass does not link $want" >&2; exit 1; }
done

printf '\nInstalled libass %s into %s\n' "$LIBASS_VERSION" "$STAGED/lib"
find "$STAGED/lib" -maxdepth 1 -type f -name "*.so.*" -printf "%9s  %f\n" | sort -k2 |
    awk '{ total += $1; print } END { printf "%9d  total\n", total }'
